import * as React from "react";
import "./App.css";
import Box from "@mui/material/Box";
//import Drawer from "@mui/material/Drawer";
import CssBaseline from "@mui/material/CssBaseline";
import Toolbar from "@mui/material/Toolbar";
import List from "@mui/material/List";
import Typography from "@mui/material/Typography";
//import Divider from "@mui/material/Divider";
import ListItem from "@mui/material/ListItem";
//import ListItemButton from "@mui/material/ListItemButton";
//import ListItemIcon from "@mui/material/ListItemIcon";
import ListItemText from "@mui/material/ListItemText";
//import InboxIcon from "@mui/icons-material/MoveToInbox";
//import MailIcon from "@mui/icons-material/Mail";
import { Breakpoint } from "react-socks";
import messaging from "./messaging.svg";
import IconButton from "@mui/material/IconButton";
import Paper from "@mui/material/Paper";
import Fab from "@mui/material/Fab";
import ListItemAvatar from "@mui/material/ListItemAvatar";
import ListSubheader from "@mui/material/ListSubheader";
import Avatar from "@mui/material/Avatar";
import MenuIcon from "@mui/icons-material/Menu";
import AddIcon from "@mui/icons-material/Add";
import ArrowBackIcon from "@mui/icons-material/ArrowBack";
import SearchIcon from "@mui/icons-material/Search";
import MoreIcon from "@mui/icons-material/MoreVert";
import { styled } from "@mui/material/styles";
import AppBar from "@mui/material/AppBar";
import Grid from "@mui/material/Grid";
import { useState } from "react";

const messages = [
  {
    id: 1,
    primary: "Brunch this week?",
    secondary:
      "I'll be in the neighbourhood this week. Let's grab a bite to eat",
    person: "/static/images/avatar/5.jpg",
  },
  {
    id: 2,
    primary: "Birthday Gift",
    secondary: `Do you have a suggestion for a good present for John on his work
      anniversary. I am really confused & would love your thoughts on it.`,
    person: "/static/images/avatar/1.jpg",
  },
  {
    id: 3,
    primary: "Recipe to try",
    secondary:
      "I am try out this new BBQ recipe, I think this might be amazing",
    person: "/static/images/avatar/2.jpg",
  },
  {
    id: 4,
    primary: "Yes!",
    secondary: "I have the tickets to the ReactConf for this year.",
    person: "/static/images/avatar/3.jpg",
  },
  {
    id: 5,
    primary: "Doctor's Appointment",
    secondary:
      "My appointment for the doctor was rescheduled for next Saturday.",
    person: "/static/images/avatar/4.jpg",
  },
  {
    id: 6,
    primary: "Discussion",
    secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
    person: "/static/images/avatar/5.jpg",
  },
  {
    id: 7,
    primary: "Summer BBQ",
    secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
    person: "/static/images/avatar/1.jpg",
  },
];

const StyledFab = styled(Fab)({
  position: "absolute",
  zIndex: 1,
  top: -30,
  left: 0,
  right: 0,
  margin: "0 auto",
});

export default function App() {
  const [selectedMessage, setSelectedMessage] = useState(null);
  const [isMessageOpen, setIsMessageOpen] = useState(false);

  const handleOpenMessage = (messageId) => {
    setSelectedMessage(messageId);
    setIsMessageOpen(true);
  };

  return (
    <div>
      <Breakpoint large up>
        <Box sx={{ flexGrow: 1 }}>
          <Grid container spacing={2}>
            <Grid item xs={3} style={{ maxHeight: "100vh", overflow: "auto" }}>
              <React.Fragment>
                <CssBaseline />
                <Paper square sx={{ pb: "50px" }} position="fixed">
                  <Typography
                    variant="h5"
                    position="sticky"
                    gutterBottom
                    component="div"
                    sx={{ p: 2, pb: 0 }}
                  >
                    Messages
                  </Typography>
                  <List sx={{ mb: 2 }}>
                    {messages.map(({ id, primary, secondary, person }) => (
                      <React.Fragment key={id}>
                        {id === 1 && (
                          <ListSubheader sx={{ bgcolor: "background.paper" }}>
                            Today
                          </ListSubheader>
                        )}

                        {id === 3 && (
                          <ListSubheader sx={{ bgcolor: "background.paper" }}>
                            Yesterday
                          </ListSubheader>
                        )}

                        <ListItem button onClick={() => handleOpenMessage(id)}>
                          <ListItemAvatar>
                            <Avatar alt="Profile Picture" src={person} />
                          </ListItemAvatar>
                          <ListItemText
                            primary={primary}
                            secondary={secondary}
                          />
                        </ListItem>
                      </React.Fragment>
                    ))}
                  </List>
                </Paper>
              </React.Fragment>
            </Grid>
            {/* Big column */}
            <Grid
              item
              xs={8}
              padding="100px"
              style={{ maxHeight: "100vh", overflow: "auto" }}
            >
              {selectedMessage ? (
                // Render open message view
                <Box sx={{ bgcolor: "background.secondary.dark" }}>
                  <div>
                    <Typography variant="h6" gutterBottom>
                      {messages[selectedMessage - 1].primary}
                    </Typography>
                    <Typography variant="body1">
                      {messages[selectedMessage - 1].secondary}
                    </Typography>
                  </div>
                </Box>
              ) : (
                // Render default view
                <img
                  src={messaging}
                  width="200px"
                  alt=""
                  className="messageimage"
                />
              )}
            </Grid>
            {/*  */}
          </Grid>
        </Box>
      </Breakpoint>

      {/* Mobile View */}
      <Breakpoint medium down>
        <React.Fragment>
          <CssBaseline />
          {isMessageOpen ? (
            <div>
              <AppBar position="fixed" color="primary">
                <Toolbar>
                  <IconButton
                    color="inherit"
                    aria-label="back"
                    onClick={() => setIsMessageOpen(false)}
                  >
                    <ArrowBackIcon />
                  </IconButton>
                  <Typography variant="h6" component="div">
                    Message
                  </Typography>
                </Toolbar>
              </AppBar>
              <div style={{ marginTop: "64px", padding: "16px" }}>
                <Typography variant="h6" gutterBottom>
                  {messages[selectedMessage - 1].primary}
                </Typography>
                <Typography variant="body1">
                  {messages[selectedMessage - 1].secondary}
                </Typography>
              </div>
            </div>
          ) : (
            <Paper square sx={{ pb: "50px" }}>
              <Typography
                variant="h5"
                gutterBottom
                component="div"
                sx={{ p: 2, pb: 0 }}
              >
                Messages
              </Typography>
              <List sx={{ mb: 2 }}>
                {messages.map(({ id, primary, secondary, person }) => (
                  <React.Fragment key={id}>
                    {id === 1 && (
                      <ListSubheader sx={{ bgcolor: "background.paper" }}>
                        Today
                      </ListSubheader>
                    )}

                    {id === 3 && (
                      <ListSubheader sx={{ bgcolor: "background.paper" }}>
                        Yesterday
                      </ListSubheader>
                    )}

                    <ListItem
                      button
                      onClick={() => handleOpenMessage(id)}
                      selected={selectedMessage === id}
                    >
                      <ListItemAvatar>
                        <Avatar alt="Profile Picture" src={person} />
                      </ListItemAvatar>
                      <ListItemText primary={primary} secondary={secondary} />
                    </ListItem>
                  </React.Fragment>
                ))}
              </List>
            </Paper>
          )}
          <AppBar
            position="fixed"
            color="primary"
            sx={{ top: "auto", bottom: 0 }}
          >
            <Toolbar>
              <IconButton color="inherit" aria-label="open drawer">
                <MenuIcon />
              </IconButton>
              <StyledFab color="secondary" aria-label="add">
                <AddIcon />
              </StyledFab>
              <Box sx={{ flexGrow: 1 }} />
              <IconButton color="inherit">
                <SearchIcon />
              </IconButton>
              <IconButton color="inherit">
                <MoreIcon />
              </IconButton>
            </Toolbar>
          </AppBar>
        </React.Fragment>
      </Breakpoint>
    </div>
  );
}
